logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123
    publisher-confirm-type: correlated # 开启publisher confirm机制
    publisher-returns: true # 开启publisher return机制